### ISSUE TITLE
x360ce input request

### ISSUE THREAD

**Issue by arnoz26** [joyrider3774/PinballX_Launcher_app#1]
Hello !
Thanks a lot for that launcher !
i've juste put it with Pinup Popper, and it works like a charm, but i have only one issue.
I have a kl25z input to navigate in my launcher and game on my pincab, i use x360ce to emulate à controller. No keyboard...
So your launcher only work with keybord and i had to install Joytokey only for your launcher.
Is that possible to imagine à xinput entry to your launcher ?

Thanks

**Comment by joyrider3774** [comment]
Hi,

I have no experience with joypad, joystick programming but i do own a real wireless xbox 360 joypad attached to my pc. If i'm able to add it in i'll be doing so, but i'll have to do research about it. It could be it wont be through xinput but using generic joypad programming so it could be that also works for xbox 360ce. But i'll be able to verify if it works with my real gamepad. If i can get it working i'll definatly will try to release a new version with joypad support

**Comment by joyrider3774** [comment]
@arnoz26 is the kl25z seen as a direct input joystick / joypad in windows then ? I noticed xbox 360ce does not seem to support keyboard input or at least i did not see it so was just wondering how the kl25z is seen in windows. My guess since you mentioned joytokey it registers as a joystick and not keyboard ?

I've got some joypad version working but it needs more work but i could navigate the launcher's app buttons using my xbox 360 controller. I'm just not that familiar with kl25z and xbox 360ce so wondering about that.

**Comment by arnoz26** [comment]
Hi and thanks for yours answers.
KL is seen as HID game controller in my system windows.X360ce put a fake Xinput dll in directory.
I've found a way to use it
With the KL25z, i can set my buttons on keyboard input instead of joystick button ( i have to keep X360ce because my plunger and tilt function are emulate with it). So i just have to change it and my game configuration to use it without Joytokey...

**Comment by joyrider3774** [comment]
@arnoz26 i released a new version with joypad support, it could be you don't need the joytokey app anymore if you setup your joystick using it directly. There is no xinput support though, i'm not going to add it but it should be possible to make it work using the hid device to make your selections. Check the release section and updated readme
