### ISSUE TITLE
Launch Timer Config

### ISSUE THREAD

**Issue by cgcreator** [joyrider3774/PinballX_Launcher_app#2]
Is it possible to make the launch timer configurable? or even disable it entirely? or reset the timer if you switch selection?

Thanks!

**Comment by joyrider3774** [comment]
sorry not going to allow that. Pinballx excpects a process to be started in a certain time. If the app does not start in a certain time it returns to the table selection menu. So if there would be no timer or longer timer you run into that problem. The timer is added specifically for this so that problem can not happen
